### ISSUE TITLE
Pretrained dataset has been unavailable

### ISSUE THREAD

**Issue by AquaLighte** [justchenhao/SaDL_CD#3]
Thanks to the author for sharing the code and data. The link of Baidu Cloud to share the pretrained data is currently unavailable. Would the author mind sharing it once more? Thanks again.

**Comment by justchenhao** [comment]
Thanks for your attention. I can still access the dataset currently in China. Can you access the Baidu Cloud in your country?

**Comment by AquaLighte** [comment]
I greatly appreciate your response. I'm also in China right now. The link is still accessible, but the page warns that 'the number of link visitors has exceeded the limit; please contact the sharer to share it again.' I'm curious if you could re-share the pre-training dataset? I eagerly await your response.

**Comment by justchenhao** [comment]
Sorry for the late reply. The updated link for the pre-training dataset is updated. Please see the readme.
